services:
  - type: web
    name: ChessServer
    runtime: python
    buildCommand: pip install websockets
    startCommand: python ws_relay_server.py
    envVars:
      - key: PORT
        value: 7778
